from marketmind.prompts.templates import (
    COMPREHENSIVE_ANALYSIS_PROMPT,
    EDUCATIONAL_ANALYSIS_PROMPT,
    EDUCATIONAL_PORTFOLIO_SECTION,
    HOLDING_ANALYSIS_PROMPT,
    LEARN_TOPIC_PROMPT,
    PORTFOLIO_ANALYSIS_PROMPT,
    PORTFOLIO_ANALYSIS_SYSTEM,
    POTENTIAL_BUY_PROMPT,
    QUICK_PRICE_PROMPT,
    STOCK_ANALYSIS_SYSTEM,
)

__all__ = [
    "COMPREHENSIVE_ANALYSIS_PROMPT",
    "EDUCATIONAL_ANALYSIS_PROMPT",
    "EDUCATIONAL_PORTFOLIO_SECTION",
    "HOLDING_ANALYSIS_PROMPT",
    "LEARN_TOPIC_PROMPT",
    "PORTFOLIO_ANALYSIS_PROMPT",
    "PORTFOLIO_ANALYSIS_SYSTEM",
    "POTENTIAL_BUY_PROMPT",
    "QUICK_PRICE_PROMPT",
    "STOCK_ANALYSIS_SYSTEM",
]
